# Generated by Django 3.0.5 on 2020-05-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='location',
            new_name='library',
        ),
    ]
